language: perl
sudo: false
perl:
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'
- '5.26'
notifications:
  slack:
    secure: iAyu4h9yE1u0+jNr6utciLxQKeDy0QY66pPpO+W/iG3BzrY09swHZiyOigGt++OJvSM90crr8Bqvbnxp1WLYchUUYubt3bVHb9eEws5iJha1nJ6PSh/FlrxLReHKzjynW/j1CwyWq0482f/hbytKsR3QWY7i+aeUQHaE6aZRckqlCskHmsVu2MYhUqZg8BCuB0P/8AFO39j9codN+24CVRaBL/Nh6OK/TFgUht4cY6W7gSp20bov7dKh7KdO3cfyuJw9JdGkhvLN4uBavfQ4ADWm1yamsHDdPanqKpQjyXmN90W1HwJ7h0qLvvgdJt6vfLjRw02QmLVfz8RPT+CCU9BSBcwET5L+VL73IMJZefh14diAQOB4VnTTRUnSY1inb/f9DIzEHJeNnNzv/mwyOses1J4N9FHZMpMntR2dVwB81ENoYvisv0qOlIzTWXnkWYg7aKKMJ4dJVjtGj+K6ILgjo1yszr3DoX/wvvC5aAh6Yuhfn53ePWeaxMPO7/y+yXLab9+NA+OIQ3Yz9MY8PgX3eVHrE8EJZfKa7j2oS0HPlNvwKWcK/MEP1oUR6WGDlMvL8idkXXJm/bY5okXYuR8jIoHUDC+qkb/nn7clsjh2fe/GScD0O7n9BytHd3yIqrpakxk+gWI/qOHO9LGh7AcAvdX1nD8IGHi2R66CI6E=
